`timescale 1ns / 1ps

// Chapter 2 top level for the GX-BIDT board and XC7A200TFBG484-2.
//
// clk_wiz_lcd is generated by scripts/create_project.tcl:
//   50.000 MHz input -> 33.333 MHz pixel clock
module top_lcd_test (
    input  wire       sys_clk,
    input  wire       sys_rst_n,
    input  wire [2:0] mode_sw,

    output wire       lcd_pclk,
    output wire       lcd_hsync,
    output wire       lcd_vsync,
    output wire       lcd_de,
    output wire       lcd_bl,
    output wire       lcd_rst_n,
    output wire [7:0] lcd_r,
    output wire [7:0] lcd_g,
    output wire [7:0] lcd_b
);

    localparam integer PIX_CLK_HZ = 50_000_000;

    wire        pix_clk;
    wire        clk_locked;
    wire        pix_rst_n;
    wire [2:0]  mode;
    wire [10:0] pixel_x;
    wire [10:0] pixel_y;
    wire        de_int;
    wire        hsync_int;
    wire        vsync_int;
    wire [23:0] pixel_rgb;
    reg         lcd_de_r;
    reg         lcd_hsync_r;
    reg         lcd_vsync_r;
    reg  [23:0] lcd_rgb_r;

    clk_wiz_lcd u_clk_wiz_lcd (
        .clk_in1  (sys_clk),
        .reset    (1'b0),
        .clk_out1 (pix_clk),
        .locked   (clk_locked)
     );

    reset_sync u_reset_sync (
        .clk    (pix_clk),
        .arst_n (clk_locked),
        .srst_n (pix_rst_n)
    );

    sync_bits #(
        .WIDTH (3)
    ) u_mode_sync (
        .clk      (pix_clk),
        .rst_n    (pix_rst_n),
        .async_in (mode_sw),
        .sync_out (mode)
    );

    lcd_power_seq #(
        .CLK_HZ         (PIX_CLK_HZ),
        .RESET_DELAY_MS (10),
        .BL_DELAY_MS    (50)
    ) u_lcd_power_seq (
        .clk       (pix_clk),
        .rst_n     (pix_rst_n),
        .lcd_rst_n (lcd_rst_n),
        .lcd_bl    (lcd_bl)
    );

    lcd_timing_800x480 u_lcd_timing (
        .pclk        (pix_clk),
        .rst_n       (pix_rst_n),
        .lcd_de      (de_int),
        .lcd_hsync   (hsync_int),
        .lcd_vsync   (vsync_int),
        .pixel_x     (pixel_x),
        .pixel_y     (pixel_y),
        .line_start  (),
        .frame_start ()
    );

    lcd_test_pattern u_lcd_test_pattern (
        .mode      (mode),
        .pixel_x   (pixel_x),
        .pixel_y   (pixel_y),
        .lcd_de    (de_int),
        .pixel_rgb (pixel_rgb)
    );

    // Change panel data/control on the falling edge. The LCD samples on the
    // following rising edge of lcd_pclk, providing approximately half a pixel
    // clock of external setup time.
    always @(negedge pix_clk or negedge pix_rst_n) begin
        if (!pix_rst_n) begin
            lcd_de_r    <= 1'b0;
            lcd_hsync_r <= 1'b1;
            lcd_vsync_r <= 1'b1;
            lcd_rgb_r   <= 24'h000000;
        end else begin
            lcd_de_r    <= de_int;
            lcd_hsync_r <= hsync_int;
            lcd_vsync_r <= vsync_int;
            lcd_rgb_r   <= de_int ? pixel_rgb : 24'h000000;
        end
    end

    assign lcd_pclk = pix_clk;
    assign lcd_hsync = lcd_hsync_r;
    assign lcd_vsync = lcd_vsync_r;
    assign lcd_de = lcd_de_r;

    assign lcd_r = lcd_rgb_r[23:16];
    assign lcd_g = lcd_rgb_r[15:8];
    assign lcd_b = lcd_rgb_r[7:0];

endmodule
